#ifndef SENSOR_SAMPLES_H
#define SENSOR_SAMPLES_H

#define NUM_OF_SAMPLES 6
#define SENSOR_DATA_HEIGHT 32
#define SENSOR_DATA_WIDTH 32

extern float s3078_samples[NUM_OF_SAMPLES][SENSOR_DATA_HEIGHT][SENSOR_DATA_WIDTH];

#endif
